'''Verses for house'''
prep = ["This is "]
verse12 = ["the horse and the hound and the horn that belonged to "]
verse11 = ["the farmer sowing his corn that kept "]
verse10 = ["the rooster that crowed in the morn that woke "]
verse9 = ["the priest all shaven and shorn that married "]
verse8 = ["the man all tattered and torn that kissed "]
verse7 = ["the maiden all forlorn that milked "]
verse6 = ["the cow with the crumpled horn that tossed "]
verse5 = ["the dog that worried "]
verse4 = ["the cat that killed "]
verse3 = ["the rat that ate "]
verse2 = ["the malt that lay in "]
verse1 = ["the house that Jack built."]
